services:
  db:
    image: postgres:16
    container_name: act2-db
    environment:
      POSTGRES_USER: profesor
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: demos
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d:ro
      - ./scripts:/scripts:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U profesor -d demos"]
      interval: 5s
      timeout: 3s
      retries: 20

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: act2-pgadmin
    depends_on:
      db:
        condition: service_healthy
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_CHECK_EMAIL_DELIVERABILITY: "False"
    ports:
      - "8080:80"
    volumes:
      - pgadmindata:/var/lib/pgadmin

volumes:
  dbdata:
  pgadmindata:
